---

- name: Restart homebridge
  systemd:
    name: homebridge
    state: restarted
    daemon_reload: true

- name: Restart homebridge-ui-x
  systemd:
    name: homebridge-ui-x
    state: restarted
    daemon_reload: true
