---
- name: Setup
  hosts: pi
  become: true
  vars_files:
    - vars.yaml
  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Config RaspberryPi | Serial
      import_tasks: tasks/raspi_config_serial.yaml
      when: raspi_config.serial is defined

    - name: Install base package
      import_tasks: tasks/base.yaml

    - name: Disable swap
      import_tasks: tasks/disable_swap.yaml

    # - name: Setup WiFi Reconnect
    #   import_tasks: tasks/wifi-reconnect.yaml

  roles:
    - nodejs
    - pbonrad.mosquitto
    - finalgene.zigbee2mqtt
    - homebridge

  # tasks:
  #   - name: Install loader for cc253x
  #     import_tasks: tasks/soft_install_cc.yaml
  #   - name: Install HomeBridge and Co
  #     import_tasks: tasks/soft_install_homebridge_co.yaml
  #   - name: Install srv-dht-mqtt
  #     include_role:
  #       name: srv-dht-mqtt
  #     when: srv_dht_mqtt_enable
