---
- name: Setup
  hosts: pi
  become: true
  vars_files:
    - vars.yaml
  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_install_compose: true
    docker_users:
      - pi
    docker_pip_executable: pip3
    pip_package: python3-pip

  pre_tasks:
    - name: Install base package
      import_tasks: tasks/base.yaml
    - name: Disable swap
      import_tasks: tasks/disable_swap.yaml
    - name: Setup WiFi Reconnect
      import_tasks: tasks/wifi-reconnect.yaml

  roles:
    - ericsysmin.chrony
    - geerlingguy.pip
    - geerlingguy.docker_arm

  tasks:
    - name: Install loader for cc253x
      import_tasks: tasks/soft_install_cc.yaml
    - name: Install HomeBridge and Co
      import_tasks: tasks/soft_install_homebridge_co.yaml
