---
# roles:
  # - name: ericsysmin.chrony
  # - name: geerlingguy.docker_arm
  # - name: geerlingguy.pip
  # Modificated from pbonrad.mosquitto
  # Don't update
  # - name: pbonrad.mosquitto

# collections:
  # - name: community.docker
