---
docker_version_armv6: 5:20.10.0~3-0~raspbian-buster
docker_version_armv7: 5:19.03.12~3-0~raspbian-buster
docker_version_arm64: 5:19.03.9~3-0~debian-buster

# Check available versions on a Pi: `apt-cache madison docker-ce`
docker_version: "{{ docker_version_armv7 if 'armv7' in ansible_architecture else docker_version_armv6 if 'armv6' in ansible_architecture else docker_version_arm64 }}"

# Whether to install recommended packages alongside docker-ce.
docker_install_recommends: false

# Whether to install Docker Compose via Pip.
docker_install_compose: true

# A list of users who will be added to the docker group.
docker_users: []

# The executable to use for Pip.
docker_pip_executable: pip3
