- name: Base | Install packages
  apt:
    state: present
    update_cache: yes
    pkg:
      - vim
      - htop
      - screen
      - git

- name: Base | Set timezone
  community.general.timezone:
    name: "{{ time_zone }}"
