# Configuring RaspberryPi
# P6 Serial
## Check, > cat /boot/cmdline.txt

- name: RaspPi.Serial | Get serial status
  shell: "raspi-config nonint get_serial"
  register: serial_status
  changed_when: False

- name: RaspPi.Serial | Get serialHW status
  shell: "raspi-config nonint get_serial_hw"
  register: serialhw_status
  changed_when: False

- name: RaspPi.Serial | Print serial status
  debug:
    msg: "Serial status is: {{ serial_status.stdout }}"

- name: RaspPi.Serial | Print serialHW status
  debug:
    msg: "SerialHW status is: {{ serialhw_status.stdout }}"

- name: RaspPi.Serial | Enable serial port
  shell: "raspi-config nonint do_serial 1"
  when: (raspi_config.serial == True) and (serial_status.stdout != '1')

- name: RaspPi.Serial | Disable serial port
  shell: "raspi-config nonint do_serial 0"
  when: (raspi_config.serial == False) and (serial_status.stdout != '0')
