- name: Create folder
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ root_directory }}"
    - "{{ root_directory }}/nginx/config"
    - "{{ root_directory }}/nginx/web"

- name: Copy nginx [config]
  copy:
    src: "template/{{ item }}"
    dest: "{{ root_directory }}/nginx/{{ item }}"
  loop:
    - config/nginx.conf
    - web/index.html

- name: Copy docker-compose
  template:
    src: template/{{ item }}.j2
    dest: "{{root_directory}}/{{ item }}"
  loop:
    - docker-compose.yaml
    - Dockerfile.homebridge
