---
galaxy_info:
  author: Alexey Matveev
  description: Install Node.js using binary packages or NodeSource repository
  min_ansible_version: "2.7"
  license: MIT
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
