homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
  user: {{ mosquitto_u_user }}
  password: {{ mosquitto_u_password }}
serial:
  port: {{ zigbee_device }}
frontend:
  port: 8088
  host: 0.0.0.0
  auth_token: {{ zigbee2mqtt_token }}
